# Generated by Django 3.1.3 on 2021-03-27 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('nit_entidad_recaudador', models.IntegerField(validators=[django.core.validators.MaxValueValidator(13)])),
                ('nombre_entidad_recaudador', models.CharField(max_length=20, null=True)),
                ('codigo_convenio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(15)])),
                ('fecha_transmision', models.DateTimeField()),
                ('secuencia_envio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('fecha_vencimiento', models.DateTimeField()),
                ('numero_registros', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)])),
                ('valor_total_transaccione', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17)])),
            ],
        ),
        migrations.CreateModel(
            name='ControlDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('nit_entidad_pagador', models.CharField(max_length=13, null=True)),
                ('nombre_entidad_pagador', models.CharField(max_length=20, null=True)),
                ('cuenta_bancaria_pagador', models.CharField(max_length=9, null=True)),
                ('numero_cuenta', models.CharField(max_length=17, null=True)),
                ('tipo_transaccion', models.CharField(choices=[(57, 'Cuenta Corriente'), (67, 'Cuenta Ahorros'), (77, 'TC VISA'), (87, 'TC MASTER'), (97, 'AMEX')], max_length=2, null=True)),
                ('valor_transaccion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17)])),
                ('indicador_validacion', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=1, null=True)),
                ('referencia_1', models.CharField(max_length=30, null=True)),
                ('referencia_2', models.CharField(max_length=30, null=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('periodos_facturados', models.CharField(max_length=2, null=True)),
                ('ciclo', models.CharField(max_length=3, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monet_api.controlregistro')),
            ],
        ),
    ]
