# Generated by Django 3.1.3 on 2021-03-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monet_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlregistro',
            old_name='valor_total_transaccione',
            new_name='valor_total_transacciones',
        ),
    ]
