# Generated by Django 3.1.3 on 2021-03-27 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monet_api', '0002_auto_20210326_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controldetalle',
            name='fecha_vencimiento',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='controlregistro',
            name='fecha_transmision',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='controlregistro',
            name='fecha_vencimiento',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)]),
        ),
    ]
