# Generated by Django 3.1.3 on 2021-03-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monet_api', '0003_auto_20210326_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlregistro',
            name='secuencia_envio',
            field=models.CharField(max_length=1),
        ),
    ]
